name : "infra-preview-deploy"

on :
  push:
    branches:
      - main
    paths:
      - 10_infr/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  preview:
    name: "Preview Deploy"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"